name: RepoD Action
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: RepoC Action
        uses: caiofaabio/repoC@0.01
            